### ISSUE TITLE
Error while running C7M2L1Item4-Start-project

### ISSUE THREAD

**Issue by Divu03** [Divu03/Android-Meta#1]
When I run the app and make a request of internet it throws this message Is It a firewall issue or problem in any file 

*This is the error message from log cat*
2024-01-10 23:59:02.845 12335-12387 NetworkSecurityConfig   com.example.littlelemon              D  Using Network Security Config from resource network_security_config debugBuild: true
2024-01-10 23:59:03.012 12335-12335 AndroidRuntime          com.example.littlelemon              E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.littlelemon, PID: 12335
                                                                                                    java.net.SocketException: socket failed: EPERM (Operation not permitted)
                                                                                                    	at java.net.Socket.createImpl(Socket.java:492)
                                                                                                    	at java.net.Socket.getImpl(Socket.java:552)
                                                                                                    	at java.net.Socket.setSoTimeout(Socket.java:1180)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
                                                                                                    	at io.ktor.client.engine.android.AndroidClientEngine$execute$2.invoke(AndroidClientEngine.kt:91)
                                                                                                    	at io.ktor.client.engine.android.AndroidClientEngine$execute$2.invoke(AndroidClientEngine.kt:90)
                                                                                                    	at io.ktor.client.engine.android.AndroidURLConnectionUtilsKt.timeoutAwareConnection(AndroidURLConnectionUtils.kt:57)
                                                                                                    	at io.ktor.client.engine.android.AndroidClientEngine.execute(AndroidClientEngine.kt:90)
                                                                                                    	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:99)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c774a22, Dispatchers.Main.immediate]
2024-01-10 23:59:03.024 12335-12335 Process                 com.example.littlelemon              I  Sending signal. PID: 12335 SIG: 9
---------------------------- PROCESS ENDED (12335) for package com.example.littlelemon ----------------------------

**Comment by Divu03** [comment]
MainActivity.kt

line 32 :                     val responseState = responseLiveData.observeAsState("").value  // correct line
mistake was :            val responseState = responseLiveData.observeAsState()

**Comment by Divu03** [comment]
Internet issue was solved without any changes in file I don't know how
